services:
  mongodb:
    image: mongo:4.4
    container_name: Mongo-container
    ports:
      - "27017:27017"
    volumes:
      - ./volumenes/mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./fotos:/fotos  # Montar la carpeta de fotos dentro del contenedor

  maven:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Maven-container
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/hogarTafi
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - .:/app # Montar el código fuente
      - ~/.m2:/root/.m2 # Caché de dependencias de Maven
    command: mvn spring-boot:run