services:
  vite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

    environment:
      - NODE_ENV=development
    restart: unless-stopped